# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Use the latest version of actions/checkout that supports Node.js 20
      - uses: actions/checkout@v3  # Updated to v3

      # Generates the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show git status for debugging
      - run: git status

      # Push changes using an updated action
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Use an updated version of the GitHub Pages action
      - uses: crazy-max/ghaction-github-pages@v3.1.3  # Updated version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Example replacement for set-output
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Example of setting environment variables using environment files
      - name: Set Env Var
        run: echo "SOME_VAR=some_value" >> $GITHUB_ENV  # Uses Environment Files

      # Example of accessing the environment variable set earlier
      - name: Access Env Var
        run: echo $SOME_VAR
